<?php

declare(strict_types=1);

/**
 * @file
 * Provides a comment entity type.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\ContentEntityForm;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

/**
 * Implements hook_theme().
 */
function bkb_comment_theme(): array {
  return [
    'source_comment' => ['render element' => 'elements'],
  ];
}

/**
 * Implements hook_theme_registry_alter
 */
function bkb_comment_theme_registry_alter(&$theme_registry) {
  $path = \Drupal::service('extension.list.module')->getPath('bkb_comment');
  $theme_registry['field__comment']['path'] = $path . '/templates';
}

/**
 * Implements hook_form_alter().
 */
function bkb_comment_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $object = $form_state->getFormObject();

  if ($object instanceof ContentEntityForm && $object->getEntity()
      ->getEntityTypeId() == 'source_comment' && $form['sources']) {
    $form['sources']['widget']['add_more']['#value'] = t('comment-form-add-more-label');
  }
}

/**
 * Implements hook_views_query_alter().
 */
function bkb_comment_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'source_comments' && !empty($view->exposed_raw_input['comment'])) {
    foreach ($query->where as &$condition_group) {
      foreach ($condition_group['conditions'] as &$condition) {
        if ($condition['field'] == 'source_comment.comment') {
          $condition['field'] = 'source_comment.comment__value';
        }
      }
    }
  }
}

/**
 * Prepares variables for comment templates.
 *
 * Default template: source-comment.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the comment information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_source_comment(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function bkb_comment_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_reassign':
      // Anonymize comments.
      $storage = \Drupal::entityTypeManager()->getStorage('source_comment');
      $source_comment_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($source_comment_ids) as $source_comment) {
        $source_comment->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function bkb_comment_user_predelete(UserInterface $account): void {
  // Delete comments that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('source_comment');
  $source_comment_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($source_comment_ids)
  );
}

/**
 * Implements hook_jsonapi_entity_filter_access.
 */
function bkb_comment_jsonapi_entity_filter_access($entity_type, $account): array {
  return ([
    JSONAPI_FILTER_AMONG_ALL => AccessResult::allowed(),
  ]);
}
