name: beliana.bkb
recipe: drupal10
config:
  php: '8.1'
  via: apache
  webroot: web
  database: mariadb:10.6
  xdebug: true
  config:
    php: .lando/php.ini

proxy:
  appserver:
    - bkb.beliana.lndo.site
  mailhog:
    - mail.lndo.site
